In [1]:
import numpy as np
a = np.array([1,2])
b = np.array([2,1])
z = np.log(a) 
print(z)


[0.         0.69314718]


In [2]:
z = np.exp(a)
print(z)


[2.71828183 7.3890561 ]


In [3]:
z = np.sqrt(a)
print(z)

[1.         1.41421356]


In [4]:
z = np.dot(a,b)
z = a.dot(b)
print(z)

4


In [5]:

#convert matrix into array

a = np.matrix([[1,2,3],[4,5,6]])
print(a)
print(a[0,0])
x = np.array(a)
print(x)
print(x.T) #transpose

[[1 2 3]
 [4 5 6]]
1
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
#no from random varuable b/w 0 & 1
r = np.random.random((2,2))
print(r)  #matrix 2×2 of random no. b/w 0&1

[[0.29580197 0.04934726]
 [0.9223876  0.69241203]]


In [7]:
#no from gaussian distribution
#with mean 0 and variance 1
h = np.random.randn(2,2)
print(h)

[[ 0.95876149  0.30226401]
 [ 0.11984257 -0.82136043]]


In [11]:
p = np.array([[1,2,3],[2,2,1],[6,7,9]])
q = np.array([[4,5],[6,7],[6,8]])
r = p.dot(q)
print(r)
pinv = np.linalg.inv(p)
print(pinv)
correct = p.dot(pinv)
print(correct)

[[ 34  43]
 [ 26  32]
 [120 151]]
[[-1.57142857 -0.42857143  0.57142857]
 [ 1.71428571  1.28571429 -0.71428571]
 [-0.28571429 -0.71428571  0.28571429]]
[[ 1.00000000e+00 -2.22044605e-16  5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00  5.55111512e-17]
 [ 1.38777878e-15  1.11022302e-15  1.00000000e+00]]


In [14]:
d = np.linalg.det(p)
print(d)

-6.999999999999999


In [12]:
di = np.diag(p)
print(di)

[1 2 9]


In [13]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
